# Generated by Django 5.2.1 on 2025-10-17 11:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentName', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('নাম', models.CharField(blank=True, max_length=50, null=True)),
                ('student_name', models.CharField(blank=True, max_length=50, null=True)),
                ('student_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('fathers_name', models.CharField(blank=True, max_length=50, null=True)),
                ('fathers_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('mothers_name', models.CharField(blank=True, max_length=50, null=True)),
                ('mothers_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('post_office', models.CharField(blank=True, max_length=50, null=True)),
                ('word', models.CharField(blank=True, max_length=30, null=True)),
                ('post_code', models.CharField(blank=True, max_length=10, null=True)),
                ('thana', models.CharField(blank=True, max_length=30, null=True)),
                ('district', models.CharField(blank=True, max_length=30, null=True)),
                ('nationality', models.CharField(blank=True, max_length=30, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('religion', models.CharField(blank=True, max_length=30, null=True)),
                ('examination', models.CharField(blank=True, max_length=30, null=True)),
                ('group', models.CharField(blank=True, max_length=30, null=True)),
                ('regi_no', models.CharField(blank=True, max_length=20, null=True)),
                ('board', models.CharField(blank=True, max_length=30, null=True)),
                ('exam_year', models.CharField(blank=True, max_length=10, null=True)),
                ('gpa', models.CharField(blank=True, max_length=10, null=True)),
                ('student_photo', models.ImageField(blank=True, null=True, upload_to='profile_pic/%Y/%m/%d/')),
                ('roll', models.IntegerField(blank=True, default=0, null=True)),
                ('approved_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='EMS.department')),
            ],
            options={
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='StudentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('নাম', models.CharField(blank=True, max_length=50, null=True)),
                ('student_name', models.CharField(blank=True, max_length=50, null=True)),
                ('student_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('fathers_name', models.CharField(blank=True, max_length=50, null=True)),
                ('fathers_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('mothers_name', models.CharField(blank=True, max_length=50, null=True)),
                ('mothers_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('post_office', models.CharField(blank=True, max_length=50, null=True)),
                ('word', models.CharField(blank=True, max_length=30, null=True)),
                ('post_code', models.CharField(blank=True, max_length=10, null=True)),
                ('thana', models.CharField(blank=True, max_length=30, null=True)),
                ('district', models.CharField(blank=True, max_length=30, null=True)),
                ('nationality', models.CharField(blank=True, max_length=30, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('religion', models.CharField(blank=True, max_length=30, null=True)),
                ('examination', models.CharField(blank=True, max_length=30, null=True)),
                ('group', models.CharField(blank=True, max_length=30, null=True)),
                ('regi_no', models.CharField(blank=True, max_length=20, null=True)),
                ('board', models.CharField(blank=True, max_length=30, null=True)),
                ('exam_year', models.CharField(blank=True, max_length=10, null=True)),
                ('gpa', models.CharField(blank=True, max_length=10, null=True)),
                ('student_photo', models.ImageField(blank=True, null=True, upload_to='request_pic/%Y/%m/%d/')),
                ('roll', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('submitted_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EMS.department')),
            ],
            options={
                'verbose_name_plural': 'Student Requests',
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('subjectCode', models.CharField(default='0', max_length=20)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='EMS.department')),
            ],
            options={
                'verbose_name_plural': 'Subjects',
            },
        ),
    ]
