# Generated by Django 5.2.1 on 2025-10-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='HonorsRegisterNO',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
