# Generated by Django 5.2.1 on 2025-10-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0002_student_honorsregisterno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/'),
        ),
    ]
