# Generated by Django 5.2.1 on 2025-10-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0003_alter_student_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrequest',
            name='student_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/'),
        ),
    ]
