# Generated by Django 5.2.1 on 2025-10-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0005_alter_student_student_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='STATUS_CHOICES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Status Choeices',
            },
        ),
    ]
