# Generated by Django 5.2.1 on 2025-10-21 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0006_status_choices'),
    ]

    operations = [
        migrations.DeleteModel(
            name='STATUS_CHOICES',
        ),
    ]
