# Generated by Django 5.2.1 on 2025-10-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0007_delete_status_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_images', models.ImageField(blank=True, default='images/carousel_images/sis.png', null=True, upload_to='images/carousel_images/')),
                ('carousel_image_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Carousel Image',
            },
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='student_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
