# Generated by Django 5.2.1 on 2025-10-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0008_carouselimage_alter_studentrequest_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/students_photo/'),
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='student_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/students_photo/'),
        ),
    ]
