# Generated by Django 5.2.1 on 2025-10-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0009_alter_student_student_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_photo',
            field=models.ImageField(blank=True, default='images/students_photo/profile.png', null=True, upload_to='images/students_photo/'),
        ),
    ]
