# Generated by Django 5.2.1 on 2025-10-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0010_alter_student_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_photo',
            field=models.ImageField(blank=True, default='images/students_photo/profile.png', null=True, upload_to='images/student_photo/'),
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='student_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/student_photo/'),
        ),
    ]
