# Generated by Django 5.2.1 on 2025-10-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0011_alter_student_student_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrequest',
            name='HonorsRegisterNO',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
