# Generated by Django 5.2.1 on 2025-10-29 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0012_studentrequest_honorsregisterno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='নাম',
            new_name='student_bangla_name',
        ),
        migrations.RenameField(
            model_name='studentrequest',
            old_name='নাম',
            new_name='student_bangla_name',
        ),
    ]
