# Generated by Django 5.2.1 on 2025-11-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0013_rename_ন_ম_student_student_bangla_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(blank=True, max_length=100, null=True)),
                ('card_image', models.ImageField(blank=True, null=True, upload_to='images/card_images/')),
                ('card_description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='carouselimage',
            options={'verbose_name_plural': 'Carousel Images'},
        ),
    ]
