# Generated by Django 5.2.1 on 2025-11-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0016_semester_alter_result_options_student_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_photo',
            field=models.ImageField(blank=True, default='images/student_photo/server4.webp', null=True, upload_to='images/student_photo/'),
        ),
    ]
