# Generated by Django 5.2.1 on 2025-11-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0018_alter_result_options_rename_gpa_result_cgpa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='total_cgpa',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
